payment:
  wxpay:
    sandbox: true
    corpId: xxx
    wxAppId: xxx
    openAppId: xxx
    mchId: xxx
    key: xx
    cert: xx
    notifyUrl: http://xxx
    refundNotifyUrl: http://xxx
  alipay:
    appId: xxx
    privateKey: xxx
    alipayPublicKey: xxx
    gatewayUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: http://xxx
    returnUrl: http://xxx
