payment:
  wxpay:
    sandbox: true
    corpId: xxx
    wxAppId: xxx
    openAppId: xxx
    mchId: xxx
    key: xx
    cert: xx
    notifyUrl: http://xxx
    refundNotifyUrl: http://xxx
  alipay:
    appId: xxx
    privateKey: xxx
    alipayPublicKey: xxx
    gatewayUrl: https://openapi.alipay.com/gateway.do
    notifyUrl: http://xxx
    returnUrl: http://xxx
  unionpay:
    merId: xxx
    privateKeyPath: /path/to/acp_test_sign.pfx
    privateKeyPwd: 000000
    acpMiddleCertPath: /path/to/acp_test_middle.cer
    acpRootCertPath: /path/to/acp_test_root.cer
    notifyUrl: http://xxx
    returnUrl: http://xxx
    sandbox: true
